### ISSUE TITLE
Error: Cannot find module '../build/Release/bson'

### ISSUE THREAD

**Issue by vladbesson** [youknowriad/intercom2db#6]
After running the intercom2db, I get errors:
```
Requesting users : page 27
Requesting users : page 28
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/intercom2db/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/intercom2db/node_modules/bson/lib/bson/index.js:3:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32) code: 'MODULE_NOT_FOUND' }

Requesting users : page 29
Requesting tags : page 1
{ Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`intercom`.`user_tags`, CONSTRAINT `user_tags_ibfk_2` FOREIGN KEY (`tag_id`) REFERENCES `tag` (`id`) ON DELETE CASCADE)
```
It is runnig on Ubuntu 16.04.2 (without Docker)

**Comment by youknowriad** [comment]
I'm sorry I don't have the time to maintain this repo anymore. If you want to PR or take over, that would be awesome. @jubianchi Are you still using this?
